config/routes.rb
Rails.application.routes.draw do
 
  get 'userrolemaps/show'

  #resources :users

  
  #root to: 'users#new'
  
  resources :sessions
  root to:'sessions#login'

  get 'sessions/login'

  get 'sessions/home'

  get 'sessions/profile'

  get 'sessions/setting'

  get 'users/new'

  resources :products

  root to: 'products#index'

  resources :userrolemaps

  root to: 'userrolemaps#index'

	
	match ':controller/:action/(:id)', via: [:get, :post]
  
  
  get "/path/to/your/tdk/page", to: "userrolemaps#tdk", as: "tdk"
   get "/path/to/your/tdk_operators/page", to: "userrolemaps#tdk_operators", as: "tdk_operators"

   get "/path/to/your/funding_operators/page", to: "userrolemaps#funding_operators", as: "funding_operators"

   get "/path/to/your/qc_operators/page", to: "userrolemaps#qc_operators", as: "qc_operators"
     get "/path/to/your/qcd_operators/page", to: "userrolemaps#qcd_operators", as: "qcd_operators"

   get "/path/to/your/authors_operators/page", to: "userrolemaps#authors_operators", as: "authors_operators"

  get "/path/to/your/addresses_operators/page", to: "userrolemaps#addresses_operators", as: "addresses_operators"
   

  get "/path/to/your/qc/page", to: "userrolemaps#qc", as: "qc"
    get "/path/to/your/qcd/page", to: "userrolemaps#qcd", as: "qcd"

  get "/path/to/your/funding/page", to: "userrolemaps#funding", as: "funding"

  get "/path/to/your/dispatched/page", to: "userrolemaps#dispatched", as: "dispatched"
get "/path/to/your/dispatchedd/page", to: "userrolemaps#dispatchedd", as: "dispatchedd"
  
   # post "/path/to/your/dispatched/page", to: "userrolemaps#dispatched", as: "dispatched"

	get "/path/to/your/welcome/page", to: "userrolemaps#welcome", as: "welcome"
	get "/path/to/your/index1/page", to: "userrolemaps#index1", as: "index1"

	get "/path/to/your/authors/page", to: "userrolemaps#authors", as: "authors"

	get "/path/to/your/addresses/page", to: "userrolemaps#addresses", as: "addresses"
  root :to => "sessions#login"
match "signup", :to => "users#new", via: [:get, :post]
match "login", :to => "sessions#login",via: [:get, :post]
match "logout", :to => "sessions#logout",via: [:get, :post]
match "home", :to => "sessions#home",via: [:get, :post]
match "profile", :to => "sessions#profile",via: [:get, :post]
match "setting", :to => "sessions#setting",via: [:get, :post]
match "dispatched", :to=> "userrolemaps#dispatched", via: [:get, :post]
end

app/models/userrolemap.rb
require 'csv'
class Userrolemap < ApplicationRecord
def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |detail|
      csv << detail.attributes
    end
  end
end
end

app/controllers/userrolemaps_controller.rb
class UserrolemapsController < ApplicationController
	before_action :authenticate_user, :only => [:index, :profile, :setting, :index1]
#before_action :save_login_state, :only => [:login, :login_attempt]
 
	def index
		@role1 = Role.select("roleID").where(roleName: 'TKA').map(&:roleID).uniq
		@operators1 = User.where("mapRoleID = ?", @role1 ).count
		@status1 = Role.select("queueStatusID").where(roleName: 'TKA').map(&:queueStatusID).uniq
		@files1 = Itemqueuedetail.where("queueStatusID =?",@status1).count
		@progress1 = Itemqueuedetail.where("queueStatusID =? AND status = '1' ",@status1).count

		@role2 = Role.select("roleID").where(roleName: 'Funding').map(&:roleID).uniq
		@operators2 = User.where("mapRoleID =?" , @role2).count
		@status2 = Role.select("queueStatusID").where(roleName: 'Funding').map(&:queueStatusID).uniq
		@files2 = Itemqueuedetail.where("queueStatusID =?",@status2).count
		@progress2 = Itemqueuedetail.where("queueStatusID = ? AND status ='1'", @status2).count

		@role3 = Role.select("roleID").where(roleName: 'QCA').map(&:roleID).uniq
		@operators3 = User.where("mapRoleID = ?", @role3).count
		@status3 = Role.select("queueStatusID").where(roleName: 'QCA').map(&:queueStatusID).uniq
		@files3 = Itemqueuedetail.where("queueStatusID =?",@status3).count
		@progress3 = Itemqueuedetail.where("queueStatusID =? AND status ='1'",@status3).count

		@status4 = Role.select("queueStatusID").where(roleName: 'Completed').map(&:queueStatusID).uniq
		@files4 = Itemqueuedetail.where("queueStatusID =?",@status4).count
		#@excel = Itemdetail.joins('INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID WHERE itemqueuedetails.queueStatusID = 1 AND itemqueuedetails.status = "0"')
		respond_to do |format|
  			format.html
  			format.csv { send_data @excel.to_csv }
  			format.xls 
		end

		#@excel1 = Itemdetail.joins('INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID WHERE itemqueuedetails.queueStatusID = 2 AND itemqueuedetails.status = "0"')
		respond_to do |format|
  			format.html
  			format.csv { send_data @excel1.to_csv }
  			format.xls 
		end
		
		respond_to do |format|
  			format.html
  			format.csv { send_data @excel2.to_csv }
  			format.xls 
		end

		respond_to do |format|
  			format.html
  			format.csv { send_data @excel3.to_csv }
  			format.xls 
		end
	end

	def tdk
		if params[:accession] != ''
		@accession =	params[:accession]
		else
		@accession	= ".*"
		end
		if params[:journal] != ''
		@journal =	params[:journal]
		else
		@journal = ".*"
		end
		@status1 = Role.select("queueStatusID").where(roleName: 'TKA').map(&:queueStatusID).uniq
		@details = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status1[0].to_s).where("itemqueuedetails.status = '1' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status1[0].to_s).where("itemqueuedetails.status = '1'")
			end
		@excel = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status1[0].to_s).where("itemqueuedetails.status = '1' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status1[0].to_s).where("itemqueuedetails.status = '1'")
			end
		#respond_to do |format|
  		#	format.html
  		#	format.csv { send_data @excel.to_csv }
  		#	format.xls 
		#end
		
	end

	def funding
		if params[:accession] != ''
		@accession =	params[:accession]
		else
		@accession	= ".*"
		end
		if params[:journal] != ''
		@journal =	params[:journal]
		else
		@journal = ".*"
		end
		@status2 = Role.select("queueStatusID").where(roleName: 'Funding').map(&:queueStatusID).uniq
		@details = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status2[0].to_s).where("itemqueuedetails.status = '1' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status2[0].to_s).where("itemqueuedetails.status = '1'")
			end
		@excel1 = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status2[0].to_s).where("itemqueuedetails.status = '1' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status2[0].to_s).where("itemqueuedetails.status = '1'")
			end
		
	end

	def qc
		if params[:accession] != ''
		@accession =	params[:accession]
		else
		@accession	= ".*"
		end
		if params[:journal] != ''
		@journal =	params[:journal]
		else
		@journal = ".*"
		end
		@status3 = Role.select("queueStatusID").where(roleName: 'QCA').map(&:queueStatusID).uniq
		@details = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status3[0].to_s).where("itemqueuedetails.status = '1' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status3[0].to_s).where("itemqueuedetails.status = '1'")
			end
		@excel2 = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status3[0].to_s).where("itemqueuedetails.status = '1' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status3[0].to_s).where("itemqueuedetails.status = '1'")
			end
		
	end

	def dispatched
		if params[:accession] != ''
		@accession =	params[:accession]
		else
		@accession	= ".*"
		end
		if params[:journal] != ''
		@journal =	params[:journal]
		else
		@journal = ".*"
		end
		@status4 = Role.select("queueStatusID").where(roleName: 'Completed').map(&:queueStatusID).uniq
		@details = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status4[0].to_s).where("itemqueuedetails.status = '0' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status4[0].to_s).where("itemqueuedetails.status = '0'")
			end
		@excel3 = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status4[0].to_s).where("itemqueuedetails.status = '0' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status4[0].to_s).where("itemqueuedetails.status = '0'")
			end
		
	end

	def authors
		if params[:accession] != ''
		@accession =	params[:accession]
		else
		@accession	= ".*"
		end
		if params[:journal] != ''
		@journal =	params[:journal]
		else
		@journal = ".*"
		end
		@status5 = Role.select("queueStatusID").where(roleName: 'Author').map(&:queueStatusID).uniq
		@details = if params[:datetimepicker1]
			Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status5[0].to_s).where("itemqueuedetails.status = '0' AND (journalSequence REGEXP ? AND accessionItemNo REGEXP ? AND itemdetails.created_at BETWEEN ? AND ?) ","#{@journal}","#{@accession}" ,"#{params[:datetimepicker1]}","#{params[:datetimepicker2]}")
			else
				Itemdetail.joins("INNER JOIN itemqueuedetails ON itemqueuedetails.itemID = itemdetails.itemID AND itemqueuedetails.queueStatusID = ", @status5[0].to_s).where("itemqueuedetails.status = '0'")
			end
		@excel4 = if params[:datetimepicker1]

app/helpers/userrolemaps_helper.rb
module UserrolemapsHelper
end

app/views/userrolemaps/dispatched.html.erb
<%= button_to 'Main Page',userrolemaps_path,method: :get,class: "button2" %>
</br>
<p>DISPATCHED</p>
<%= form_tag(dispatched_path, method: :get) do %>
<table class="table">
<tr class="tr">
<% @my_date1 = Time.now - 4.years %>
<% @my_date2 = Time.now %>
<td>Start Date<%= select_date( @my_date1 ,prompt: true,prefix: :start_date) %></td>
<td>Last Date<%= select_date( @my_date2 ,prompt: true,prefix: :end_date) %></td>
<td>AccessionItemNo:<%= text_field_tag :accession %></td>
<td>JournalSequence:<%= text_field_tag :journal %></td>
<td>SDate:<div class="container" style="width:100%;">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <!-- <input type='text' class="form-control" /> -->
                    <div class="input-group-addon" style="width:100%;">
                        <%= text_field_tag :datetimepicker1 %>
                        <span class="glyphicon glyphicon-calendar"></span>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
    $('#datetimepicker1').datetimepicker({
        format : 'YYYY-MM-DD HH:mm',
        defaultDate: "11/1/2013"
                    
    });
});
        </script>
    </div>
</div></td>
<td>EDate:<div class="container"  style="width:100%;">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker2'>
                    <!-- <input type='text' class="form-control" /> -->
                    <div class="input-group-addon"  style="width:100%;">
                        <%= text_field_tag :datetimepicker2 %>
                        <span class="glyphicon glyphicon-calendar"></span>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                var date=new Date().getFullYear();
                var month=parseInt(new Date().getMonth());
                month=month+1;
                date=date+"-"+month.toString();
                date=date+"-"+new Date().getDate();
                date=date+" "+new Date().getHours();
                date=date+":"+new Date().getMinutes();
                console.log(date.toString());
    $('#datetimepicker2').datetimepicker({
        format : 'YYYY-MM-DD HH:mm',
        defaultDate: date.toString()
                    
    });
    
});
        </script>
    </div>
</div></td>

<td><%= submit_tag 'Search' %></td>
</tr>
</table>
<% end %>

	<table class="table">
	<tr class="tr">
		<td>Date</td>
		<td>ItemID</td>
		<td>AccessionItemNo</td>
		<td>JournalSequence</td>
		<td>Priority</td>
		<td>Workflow</td>
        <td>JobName</td>	
	</tr>
<% for t in @details %>
	<tr class="tr">
	<td><%= t.created_at %></td>
	<td><%= t.itemID %></td>
	<td><%= t.accessionItemNo %></td>
	<td><%= t.journalSequence %></td>
	<td><%= t.priority %>
		<%= form_tag(:action => 'updateDispatched') do %>
		<%= text_field_tag(:priority) %>
		<%= hidden_field_tag 'id' , t.itemID %>
		<%= submit_tag("Change") %>
  		<% end %></td>
	<td><%= link_to 'Show', {:action => 'show', :id => t.itemID}, :onclick=>"window.open(this.href,'show_details', 'height=600, width=600');return false;" %></td>
    <td><%= t.jobName %></td>
	</tr>
<% end %>
</table>
<p style="text-shadow: 0px 0px black;">
Download:
<%= link_to "Excel", dispatched_path(request.parameters.merge({format: :xls})), 
    download: 'dispatched.xls' %>
</p>

app/views/userrolemaps/index.html.erb
<script>

			function Gauge1(el) {

    // ##### Private Properties and Attributes

    var element,      // Containing element for the info component
        data,         // `.gauge__data` element
        needle,       // `.gauge__needle` element
        value = 0.0,  // Current gauge value from 0 to 1
        prop;         // Style for transform

    // ##### Private Methods and Functions

    var setElement = function(el) {
        // Keep a reference to the various elements and sub-elements
        element = el;
        data = element.querySelector(".gauge__data");
        needle = element.querySelector(".gauge__needle");
    };

    var setValue = function(x) {
        value = x;
        var turns = -0.5 + (x * 0.5);
        data.style[prop] = "rotate(" + turns + "turn)";
        needle.style[prop] = "rotate(" + turns + "turn)";
    };

    // ##### Object to be Returned

    function exports() { };

    // ##### Public API Methods

    exports.element = function(el) {
        if (!arguments.length) { return element; }
        setElement(el);
        return this;
    };

    exports.value = function(x) {
        if (!arguments.length) { return value; }
        setValue(x);
        return this;
    };

    // ##### Initialization

    var body = document.getElementsByTagName("body")[0];
    ["webkitTransform", "mozTransform", "msTransform", "oTransform", "transform"].
        forEach(function(p) {
            if (typeof body.style[p] !== "undefined") { prop = p; }
        }
    );

    if (arguments.length) {
        setElement(el);
    }

    return exports;

};</script>

<script>

            function Gauge2(el) {

    // ##### Private Properties and Attributes

    var element,      // Containing element for the info component
        data,         // `.gauge__data` element
        needle,       // `.gauge__needle` element
        value = 0.0,  // Current gauge value from 0 to 1
        prop;         // Style for transform

    // ##### Private Methods and Functions

    var setElement = function(el) {
        // Keep a reference to the various elements and sub-elements
        element = el;
        data = element.querySelector(".gauge__data");
        needle = element.querySelector(".gauge__needle");
    };

    var setValue = function(x) {
        value = x;
        var turns = -0.5 + (x * 0.5);
        data.style[prop] = "rotate(" + turns + "turn)";
        needle.style[prop] = "rotate(" + turns + "turn)";
    };

    // ##### Object to be Returned

    function exports() { };

    // ##### Public API Methods

    exports.element = function(el) {
        if (!arguments.length) { return element; }
        setElement(el);
        return this;
    };

    exports.value = function(x) {
        if (!arguments.length) { return value; }
        setValue(x);
        return this;
    };

    // ##### Initialization

    var body = document.getElementsByTagName("body")[0];
    ["webkitTransform", "mozTransform", "msTransform", "oTransform", "transform"].
        forEach(function(p) {
            if (typeof body.style[p] !== "undefined") { prop = p; }
        }
    );

    if (arguments.length) {
        setElement(el);
    }

    return exports;

};</script>

<div style="padding-bottom: :20px;">
<h2>PROCESS A</h2>
<table class="indextable" >
<tr>
	<td class="head1">TDK</td>
	<td class="head2">FUNDING</td>
	<td class="head3">QC</td>
	<td class="head4">DISPATCHED</td>
</tr>
<tr>
<td class="td1">
<!-- <div class = 'levels'>

 -->
<%= link_to 'Process Details',tdk_path(@files1),class:"button1" %>
<br>
</br>
<%= link_to 'Operators Details', tdk_operators_path,class:"button1" %>
</br>
</br>
<p>No.of operators:<%= @operators1 %></p>
<p>No.of files:<%= @files1 %></p>
<!-- <input type="hidden" id="angle" value="<%= @files1 %>"> 
 --><p>Files in progress:<%= @progress1 %></p>
</br>
<input type="hidden" id="gauge1" value="<%= @files1 %>">
<input type="hidden" id="tot1" value="<%= @progress1 %>">
<div class="gauge gauge--liveupdate" id="meter1">
        	<div class="gauge__container">
        		<div class="gauge__marker"></div>
        		<div class="gauge__background"></div>
        		<div class="gauge__center" style="background-color: #009999;"></div>
        		<div class="gauge__data"></div>
        		<!-- <div class="gauge__needle"></div> -->
        	</div>
        	<div class="gauge__labels mdl-typography__headline">
            	<span class="gauge__label--low"></span>
            	<span style="text-align: center; font-weight: bold; font-size: xx-large; text-shadow: 2px 2px black;" class="gauge__label--spacer" id="span1" ></span>
            	<span class="gauge__label--high"></span>
        	</div>
    	</div>

<script>
	var gauge = new Gauge1(document.getElementById("meter1"));
		var x=parseFloat(document.getElementById("tot1").value,10)/parseFloat(document.getElementById("gauge1").value,10);
		document.getElementById("span1").innerHTML=(x*100).toFixed(1)+"%";
		console.log(x.toString());
gauge.value(x);
</script>

<!-- </div>
 --></td>

<td class="td2">
<!-- <div class = "levels">
 -->
<%= link_to 'Process Details',funding_path(@files2), class:"button2" %>
<br>
</br>
<%= link_to 'Operators Details', funding_operators_path, class:"button2" %>
</br>
</br>
<p>No.of operators:<%= @operators2 %></p>
<p>No.of files:<%= @files2 %></p>
<p>Files in progress:<%= @progress2 %></p>
</br>
<input type="hidden" id="gauge2" value="<%= @files2 %>">
<input type="hidden" id="tot2" value="<%= @progress2 %>">
<div class="gauge gauge--liveupdate" id="meter2">
        	<div class="gauge__container">
        		<div class="gauge__marker"></div>
        		<div class="gauge__background"></div>
        		<div class="gauge__center" style="background-color: #ffd11a;"></div>
        		<div class="gauge__data"></div>
        		<!-- <div class="gauge__needle"></div> -->
        	</div>
        	<div class="gauge__labels mdl-typography__headline">
            	<span class="gauge__label--low"></span>
            	<span style="text-align: center; font-weight: bold; font-size: xx-large; text-shadow: 2px 2px black;" class="gauge__label--spacer" id="span2"></span>
            	<span class="gauge__label--high"></span>
        	</div>
    	</div>

<script>
	var gauge = new Gauge2(document.getElementById("meter2"));
		var x=parseFloat(document.getElementById("tot2").value,10)/parseFloat(document.getElementById("gauge2").value,10);
		document.getElementById("span2").innerHTML=(x*100).toFixed(1)+"%";
		console.log(x.toString());
gauge.value(x);
</script>
</td>
<td class="td3">
<!-- <div class = "levels"> -->
<%= link_to 'Process Details',qc_path(@files3), class:"button3" %>
<br>
</br>
<%= link_to 'Operators Details', qc_operators_path, class:"button3" %>
</br>
</br>
<p>No.of operators:<%= @operators3 %></p>
<p>No.of files:<%= @files3 %></p>
<p>Files in progress:<%= @progress3 %></p>
</br>
<input type="hidden" id="gauge3" value="<%= @files3 %>">
<input type="hidden" id="tot3" value="<%= @progress3 %>">
<div class="gauge gauge--liveupdate" id="meter3">
        	<div class="gauge__container">
        		<div class="gauge__marker"></div>
        		<div class="gauge__background"></div>
        		<div class="gauge__center" style="background-color:#33ff99; "></div>
        		<div class="gauge__data"></div>
        		<!-- <div class="gauge__needle"></div> -->
        	</div>
        	<div class="gauge__labels mdl-typography__headline">
            	<span class="gauge__label--low"></span>
            	<span style="text-align: center; font-weight: bold; font-size: xx-large; text-shadow: 2px 2px black;
" class="gauge__label--spacer" id="span3"></span>
            	<span class="gauge__label--high"></span>
        	</div>
    	</div>

<script>
	var gauge = new Gauge1(document.getElementById("meter3"));
		var x=parseFloat(document.getElementById("tot3").value,10)/parseFloat(document.getElementById("gauge3").value,10);
		document.getElementById("span3").innerHTML=(x*100).toFixed(1)+"%";
		console.log(x.toString());
gauge.value(x);
</script>

</td>
<td class="td4">
<!-- <div class = "levels"> -->
<%= link_to 'Process Details',dispatched_path(@files4), class:"button4" %>
</br>
</br>

<p>No.of files:<%= @files4 %></p>
</br>
</br>
</br>
</br>
</br>
</br>
<input type="hidden" id="gauge4" value="<%= @files4 %>">
<div class="gauge gauge--liveupdate1" id="meter4">
        	<div class="gauge__container">
        		<div class="gauge__marker"></div>
        		<div class="gauge__background"></div>
        		<div class="gauge__center" style="background-color: #cc3399;"></div>
        		<div class="gauge__data"></div>
        		<!-- <div class="gauge__needle"></div> -->
        	</div>
        	<div class="gauge__labels mdl-typography__headline">
            	<span class="gauge__label--low"></span>
            	<span style="text-align: center; font-weight: bold; font-size: xx-large; text-shadow: 2px 2px black;" class="gauge__label--spacer" id="span4"></span>
            	<span class="gauge__label--high"></span>
        	</div>
    	</div>

<script>
	var gauge = new Gauge2(document.getElementById("meter4"));
		var x=parseFloat(document.getElementById("gauge1").value,10)+parseFloat(document.getElementById("gauge2").value,10)+parseFloat(document.getElementById("gauge3").value,10)+parseFloat(document.getElementById("gauge4").value,10);
		x=parseFloat(document.getElementById("gauge4").value,10)/x;
		document.getElementById("span4").innerHTML=(x*100).toFixed(1)+"%";
		console.log(x.toString());
gauge.value(x);
</script>
</td>
</tr>
</table>
</div>